spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/coc_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    hibernate:
      default_schema: public
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    ignore-missing-migrations: true
    validate-on-migrate: true
    out-of-order: true
    schemas: public
    locations: classpath:db/migration
